import test from 'node:test';import assert from 'node:assert/strict';
import {SCENES,clamp,smoothstep,mix,initialState,reduceState,progressFromFrame,sceneIndex,evaluateScene} from '../runtime/scene-core.mjs';
import {renderSceneSVG,escapeXML} from '../specimen/draw.mjs';
test('six distinct narrative scenes',()=>assert.equal(new Set(SCENES.map(s=>s.id)).size,6));
test('clamp normal bounds',()=>{assert.equal(clamp(-1),0);assert.equal(clamp(2),1);assert.equal(clamp(.3),.3)});
for(const bad of [NaN,Infinity,-Infinity,'1',null,undefined])test('reject nonfinite/type '+String(bad),()=>assert.throws(()=>clamp(bad)));
test('smoothstep endpoints and midpoint',()=>{assert.equal(smoothstep(0),0);assert.equal(smoothstep(1),1);assert.equal(smoothstep(.5),.5)});
test('mix is affine',()=>assert.equal(mix(2,4,.5),3));
test('fresh initial state is not shared mutable state',()=>{const a=initialState();a.aperture=0;assert.equal(initialState().aperture,.62)});
test('reducer does not mutate',()=>{const s=initialState(),copy=structuredClone(s);reduceState(s,{type:'aperture',value:.8});assert.deepEqual(s,copy)});
test('aperture clamped',()=>assert.equal(reduceState(initialState(),{type:'aperture',value:20}).aperture,1));
test('finish persists through every scene',()=>{let s=reduceState(initialState(),{type:'finish',value:'graphite'});for(let i=0;i<=100;i++)assert.equal(evaluateScene(i/100,s).finish,'graphite')});
test('invalid finish fails',()=>assert.throws(()=>reduceState(initialState(),{type:'finish',value:'made-up'})));
test('section requires boolean',()=>assert.throws(()=>reduceState(initialState(),{type:'section',value:'yes'})));
test('pointer bounded',()=>{const s=reduceState(initialState(),{type:'pointer',x:20,y:-20});assert.equal(s.pointerX,1);assert.equal(s.pointerY,-1)});
test('pointer nonfinite fails',()=>assert.throws(()=>reduceState(initialState(),{type:'pointer',x:NaN,y:0})));
test('unknown action fails',()=>assert.throws(()=>reduceState(initialState(),{type:'noop'})));
test('missing action fails',()=>assert.throws(()=>reduceState(initialState(),null)));
test('reset recovers initial configuration',()=>assert.deepEqual(reduceState({...initialState(),finish:'ceramic',section:true},{type:'reset'}),initialState()));
test('scene final index stays in range',()=>assert.equal(sceneIndex(1),5));
test('negative/outside progress clamps',()=>{assert.equal(sceneIndex(-1),0);assert.equal(sceneIndex(2),5)});
test('frame first last and one-frame mapping',()=>{assert.equal(progressFromFrame(0,100),0);assert.equal(progressFromFrame(99,100),1);assert.equal(progressFromFrame(0,1),0)});
for(const [f,d] of [[0,0],[-1,4],[4,4],[.5,4],[0,2.5],[Infinity,4]])test(`invalid frame ${f}/${d}`,()=>assert.throws(()=>progressFromFrame(f,d)));
test('evaluator deterministic',()=>assert.deepEqual(evaluateScene(.48),evaluateScene(.48)));
test('reverse seek returns identical state',()=>{const a=evaluateScene(.2);evaluateScene(.9);assert.deepEqual(evaluateScene(.2),a)});
test('pose finite throughout entire story',()=>{for(let i=0;i<=1000;i++){const f=evaluateScene(i/1000);for(const v of Object.values(f.pose))assert.ok(Number.isFinite(v));assert.ok(f.pose.scale>0)}});
test('ordinary scene boundaries are spatially continuous',()=>{for(let i=1;i<6;i++){const a=evaluateScene(i/6-1e-8).pose,b=evaluateScene(i/6).pose;for(const k of Object.keys(a))assert.ok(Math.abs(a[k]-b[k])<1e-5,k)}});
test('reduced motion eliminates pointer and in-scene camera travel',()=>{const s={...initialState(),pointerX:.8,pointerY:.4};const a=evaluateScene(.51,s,{reducedMotion:true}),b=evaluateScene(.59,s,{reducedMotion:true});assert.equal(a.pointerX,0);assert.equal(a.pointerY,0);assert.deepEqual(a.pose,b.pose)});
test('section retains assembly separation',()=>assert.ok(evaluateScene(0,{...initialState(),section:true}).pose.explode>=.8));
test('SVG is deterministic',()=>assert.equal(renderSceneSVG(evaluateScene(.5)),renderSceneSVG(evaluateScene(.5))));
test('SVG has no external reference or executable markup',()=>{const s=renderSceneSVG(evaluateScene(.2));assert.ok(!/<script|<foreignObject|<image|href=|onload=/i.test(s))});
test('aperture changes visible geometry',()=>assert.notEqual(renderSceneSVG(evaluateScene(.5,{...initialState(),aperture:.2})),renderSceneSVG(evaluateScene(.5,{...initialState(),aperture:.8}))));
test('finish changes surface markup',()=>assert.notEqual(renderSceneSVG(evaluateScene(.5,{...initialState(),finish:'silver'})),renderSceneSVG(evaluateScene(.5,{...initialState(),finish:'graphite'}))));
test('portal is substantially larger than establishing object',()=>assert.ok(evaluateScene(.81).pose.scale>evaluateScene(0).pose.scale*4));
test('XML escaping',()=>assert.equal(escapeXML('<a "x">&'), '&lt;a &quot;x&quot;&gt;&amp;'));
for(const [w,h] of [[0,400],[400,0],[Infinity,400],[17000,400],[-1,400]])test(`invalid SVG dimensions ${w}/${h}`,()=>assert.throws(()=>renderSceneSVG(evaluateScene(0),w,h)));
