name: Trufflehog Secrets Scan
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:

jobs:
  trufflehog:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          fetch-depth: 0
      - uses: trufflesecurity/trufflehog@8708801319700a16c56abb86628803ba766d5563 # main 2026-07-17
        with:
          version: 3.95.9
          extra_args: --only-verified
